namespace ClaimsTriageWorkflow.Models;

/// <summary>Raw claim as received from the customer channel.</summary>
public record InboundClaim(
    string ClaimId, // UUID generated by caller if not found in text
    string RawText // unstructured customer message, unmodified
);
